### ISSUE TITLE
v10 support request

### ISSUE THREAD

**Issue by germandrewboat** [HadaIonut/EEEG-importer#11]
Attached are the errors thrown when trying to import the code from EEEG Importer into Foundry's latest stable v10 build

![errors](https://user-images.githubusercontent.com/90376395/190531082-271c5c45-eaad-4763-a0b5-5128402c4351.jpg)

**Comment by RinVindor** [comment]
Is there a timeline for when this will get updated? I had joined the patreon for this feature especially.

**Comment by HadaIonut** [comment]
I will look into how complicated this issue is, but I am not planning to keep my modules up to date. So it's really likely that this will be my last update for this module.

I am pretty busy with work and university at the moment and it's really annoying how foundry keeps changing a lot of stuff for no reason in every update.

**Comment by HadaIonut** [comment]
I have published a patch for this issue, it should work fine. One loss is the nice paths for selecting where to put the folders because the `.parent` property is broken in foundry 10.
