### ISSUE TITLE
v11 Support

### ISSUE THREAD

**Issue by ImNotYourBudde** [HadaIonut/EEEG-importer#13]
As the title suggests, just hoping to get Version 11 working. The module has no functionality with it. Didn't see anything in the EG discord so figured I'd see if I could get some notice on here. Any help would be amazing!

**Comment by germandrewboat** [comment]
@ryceg Please get somebody to update this for v11. (by the way, v12 is in prototyping now) Some of us use the Patreon _**exactly**_ for the features you advertise are updated on your Patreon. 

Otherwise, adjust this description please.
![image](https://github.com/HadaIonut/EEEG-importer/assets/90376395/ea2e4e51-aad9-4c32-a4b8-d9e13122d115)
