### ISSUE TITLE
Does not work on FVTT 9.23

### ISSUE THREAD

**Issue by kirerellim** [HadaIonut/EEEG-importer#8]
I figure this is probably known but it case it hasn't been mentioned the most recent update appears to have broken the importer. Here is the error thrown. It also might be something on my side my coding knowledge is very limited

![Error Code](https://user-images.githubusercontent.com/39993026/148578458-05bf2a1e-92b7-47cc-a94a-de6c8779128b.png)
.

**Comment by germandrewboat** [comment]
Partly bumping here; but also I emailed Hada a few weeks ago: he's pretty busy with schooling at the moment due to it being crunch time/exam season. 

He told me he would continue development on it when he can. I also informed him of the League of Foundry VTT developers discord in case he didn't want to maintain the module, as there are people there who would, usually.

**Comment by HadaIonut** [comment]
Finally I got the time to fix it, an update will be released today

**Comment by germandrewboat** [comment]
Thank you so much. This is a lifesaver and I hope you're doing well.
